version: '3.1'

services:
  
  urltojson-env:
    image: e77b7e8d53b4 
    environment:
      userdb: postgres
      namedb: postgres
      sslmodedb: disable
      hostdb: rdsdb.cl7qr0tjero7.us-west-2.rds.amazonaws.com
      passdb: p0Tgr_aws2248
    ports:
      - 5432:5432
      - 8181:8181