#apiVersion: v1
#kind: Namespace
#metadata:
#  name: stage
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: prod
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urltojson-app
  namespace: prod
spec:
  selector:
    matchLabels:
      app: urltojson-app
  replicas: 3
  template:
    metadata:
      labels:
        app: urltojson-app
    spec:
      containers:
      - name: urltojson
        image: ruslangr/urltojson:latest
        env:
        - name: hostdb
          valueFrom: 
            configMapKeyRef: 
              name: urltojson-configmap
              key: hostdb
        - name: sslmodedb
          valueFrom: 
            configMapKeyRef: 
              name: urltojson-configmap
              key: sslmodedb
        - name: namedb
          valueFrom: 
            configMapKeyRef: 
              name: urltojson-configmap
              key: namedb
        - name: userdb
          valueFrom: 
            configMapKeyRef: 
              name: urltojson-configmap
              key: userdb
        - name: passdb
          valueFrom:
            secretKeyRef:
              name: urltojson-secret
              key: passdb
---
apiVersion: v1
kind: Service
metadata:
  name: urltojson-app
spec:
  type: LoadBalancer
  selector:
    app: urltojson-app
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181