#apiVersion: v1
#kind: Namespace
#metadata:
#  name: stage
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: prod
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urltojson-app
spec:
  selector:
    matchLabels:
      app: urltojson-app
  replicas: 1
  template:
    metadata:
      labels:
        app: urltojson-app
    spec:
      containers:
      - name: urltojson
        image: ruslangr/urltojson:latest
#        ports:
#        - containerPort: 8181
#        ports:
#        - containerPort: 5432 

  
