apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: urltojson-app
spec:
  containers:
  - name: urltojson
    image: ruslangr/urltojson:latest
#    ports:
#      - containerPort: 8181
#    ports:
#      - containerPort: 5432 
