apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-27T07:31:58Z"
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  name: quickstart-kb-http
  namespace: log
  ownerReferences:
  - apiVersion: kibana.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Kibana
    name: quickstart
    uid: 28a2bf88-a0fd-410f-9097-d5b510b3a65f
  resourceVersion: "156919"
  uid: 0d1fde2b-da53-4c4a-96f5-83a5bd3f7108
spec:
  clusterIP: 172.20.238.91
  clusterIPs:
  - 172.20.238.91
  ports:
  - name: https
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}