apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-27T05:22:34Z"
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
  name: quickstart-es-http
  namespace: log
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Elasticsearch
    name: quickstart
    uid: b364b8ff-8576-44a4-babf-f69bb00b06a4
  resourceVersion: "141937"
  uid: 6528306c-cdca-49b1-acef-f83563932414
spec:
  clusterIP: 172.20.174.207
  clusterIPs:
  - 172.20.174.207
  ports:
  - name: https
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}